nshop/accounts/urls.py
from django.urls import path, include
from . import views

app_name='accounts'
urlpatterns = [
    path('signup', views.signup_view, name='signup'),
    #path('', views.HomeView, name='home'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
]

nshop/categories/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'category'


urlpatterns = [
	path('', views.HomeView.as_view(), name='home'),
	path('category/<slug:category_slug>/', views.HomeView.as_view(), name='category_filter'),
	path('<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nshop/nshop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('categories.urls', namespace='category')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#urlpatterns += staticfiles_urlpatterns()

nshop/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser 
from .managers import UserManager
from flask_sqlalchemy import SQLAlchemy
class User(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True)
    phone_number = models.CharField(max_length=11, unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField()
    user_name = models.CharField(max_length=30, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    #* * * * *if i changed the usernamefield i must delete the fields from the required one*****
    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['email', 'user_name', 'first_name', 'last_name', 'age']
    #**** in managers the order of argus for creatuser is based on userfield then requiredfield

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True
    @property
    def is_staff(self):
        return self.is_admin

nshop/categories/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=150)
    slug = models.SlugField(max_length=150, unique=True)
    image = models.ImageField(upload_to='category/', null=True, blank=True)
    

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    
    def get_absolute_url(self):
        return reverse('category:category_filter', args=[self.slug,])

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to='products/')
    description = models.TextField()
    price = models.IntegerField()
    number = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category:product_detail', args=[self.slug,])

nshop/accounts/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from flask_sqlalchemy import SQLAlchemy

class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'phone_number', 'age', 'user_name')

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user



class UserChangeForm(forms.ModelForm):
    
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('phone_number', 'email', 'first_name', 'last_name', 'age', 'user_name','password', 'is_active', 'is_admin')

nshop/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django.contrib.auth import login, authenticate , logout
from .forms import UserCreationForm

def HomeView(request):
    return render(request, 'categories/home.html')

def signup_view(request):
    if request.method=='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user= form.save()
            login(request, user)
            return redirect('category:home')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method=='POST':
        form=AuthenticationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('category:home')
    else:
        form=AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect('category:home')
    else:
        return render(request, 'categories/home.html')

nshop/categories/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .models import Product, Category
from django.contrib import messages

class HomeView(View):
	def get(self, request, category_slug=None):
		products = Product.objects.filter(available=True)
		categories = Category.objects.all()
		if category_slug:
			category = Category.objects.get(slug=category_slug)
			products = products.filter(category=category)
		return render(request, 'home.html', {'products':products, 'categories':categories})

class ProductDetailView(View):
	def get(self, request, slug):
		product = get_object_or_404(Product, slug=slug)
		return render(request, 'detail.html', {'product': product})

nshop/nshop/views.py
from django.shortcuts import render
from django.http import HttpResponse

#def HomeView(request):
#    return render(request, 'home.html')

nshop/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{%block content%}
    <form class="" action="{% url 'accounts:login' %}" method="post">
        {{form}}
        {% csrf_token %}
        <input type="submit" value="login">
    </form>
{%endblock%}

nshop/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{%block content%}
        
    <h2>Sign up Form</h2>
    <form method="post">
    {% csrf_token %}
    {% for field in form %}
        <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
        {% endfor %}
        </p>
    {% endfor %}
    <button type="submit">Sign up</button>
    </form>
{%endblock%}

nshop/categories/templates/detail.html
{%extends 'base.html'%}
{% load static %}

{%block content%}
    
    <h2> {{ product.name }}</h2>
    <small>{{ product.created }}</small><br/>
    <p>{{ product.price }} Toman</p>
    <p>{{ product.number }} Number</p>
    <img src="{{ product.image.url }}" style="width: 300px;">
    <p> {{ product.description }}</p>

{%endblock%}

nshop/categories/templates/home.html
{%extends 'base.html'%}
{% load static %}

{% block extra_headers %}
<link rel="stylesheet" href="{% static 'categories/css/styles.css' %}">
{% endblock %}

{%block content%}
    <h2>Categories</h2>
    {% for category in categories %}
            
        <div class="col-sm-4" style="width: 18rem; display: inline-block;"> 
            <div class="panel panel-primary">
                <div class="panel-body">
                    <img src="{{ category.image.url }}" class="img-responsive" style="width: 300px; height: 300px;">
                    <a href="{{ category.get_absolute_url }}" class="panel-footer">{{ category.name }}</a>
                </div>
            </div>
        </div>
        
    {% endfor %}
    <br/><br/>
    <h2>All Products</h2>
    {% for product in products %}
        <div class="card" style="width: 18rem; display: inline-block;">
            <img src="{{ product.image.url }}" class="card-img-top" style="width: 300px; height: 300px;">
            <div class="card-body">
                <a href="{{ product.get_absolute_url }}" class="card-title">{{ product.name }}</a>
            </div>
        </div>
    {% endfor %}
{%endblock%}

nshop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="UTF-8">
        <title>Online Shop</title>
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <h1>Online Shop</h1>
    <body>

        {% include 'navbar.html' %}<br/><br/>
        {%block content%}
        
        {%endblock%}
    </body>
</html>

nshop/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'category:home' %}">Home</a>
            {% if request.user.is_authenticated %}
            <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">logout</button>
            </form>
            <br/>

            {% else %}
            <a class="nav-link active" href="{% url 'accounts:signup' %}">SignUp</a>
            {% csrf_token %}
            <a class="nav-link active" href="{% url 'accounts:login' %}">Login</a>
            {%endif%}
        </div>
    </div>
</nav>